config/routes.rb
Rails.application.routes.draw do

  root :to => redirect("/#{Project.default_locale}")
  root to: "home#archive", locale: Project.default_locale.to_sym

  scope "/:locale", :constraints => {:locale => /[a-z]{2}/} do
    devise_for :user_accounts, :controllers => {sessions: 'sessions', passwords: 'passwords'}, skip: [:registrations]
    resources :accounts, only: [:show, :update] do
      member do
        get :confirm_new_email
      end
    end
    resources :user_registrations do
      member do
        post :confirm
        get :activate
        #post :subscribe
        #post :unsubscribe
      end
    end

    localized do
      resources :contributions, only: [:create, :destroy]
      #resources :histories, only: [:create, :update, :destroy]
      resources :biographical_entries, only: [:create, :show, :update]
      resources :photos, only: [:create, :update, :destroy]
      resources :segments, only: [:create, :update, :index, :destroy, :show]
      resources :registry_entries, only: [:create, :show, :update, :index, :destroy] 
      resources :registry_hierarchies, only: [:create, :destroy]
      resources :registry_references, only: [:create, :update, :destroy, :index]
      resources :registry_reference_types, only: [:create, :update, :index, :destroy]
      resources :annotations, only: [:create, :update, :destroy]
      get 'locations', to: 'registry_references#locations', :as => :locations

      resources :people do
        #resources :histories, only: [:create, :update, :destroy]
        resources :biographical_entries, only: [:destroy]
      end

      %w{archive  faq_archive_contents faq_index faq_searching faq_technical map_tutorial}.each do |site|
        get site, to: "home##{site}", as: site
        get '/',  to: "home#archive", as: :home
      end

      #get 'map', to: 'registry_references#map', :as => :public_map
      #get 'mapframe', to: 'registry_references#map_frame', :as => :map_frame

      resources :collections, only: [:show, :index] do
        collection do
          get :countries
        end
      end

      resources :transcripts, only: [:new, :create]
      resources :uploads, only: [:new, :create]

      #post 'upload_transcript', to: 'interviews#upload_transcript', as: :upload_transcript
      #get 'upload_transcript', to: 'interviews#upload_transcript', as: :upload_transcript

      put 'update_speakers/:id', to: 'interviews#update_speakers'

      resources :interviews do
        member do 
          get :doi_contents
          get :headings
          get :initials
          #get :references
          get :ref_tree
        end
        collection do 
          post :dois
          #get :stills
        end
        #resources :registry_entries, only: [:show]
        resources :contributions, only: [:create, :destroy]
        resources :photos, only: [:create, :update, :destroy]
        resources :registry_references, only: [:create, :update, :destroy]
        resources :segments, only: [:create, :update, :index, :destroy]
        resources :tapes do
          collection do
            get :playlist
          end
          member do
            get :transcript
          end
        end
      end

      resources :searches, only: [:new, :facets, :archive, :interview] do
        collection do
          get :facets
          get :archive
          get :export_archive_search
          get :interview
          get :registry_entry
        end
      end
    end

    resources :user_contents do
      collection do
        get :segment_annotation
        post :create_annotation
        post :sort
      end
      member do
        patch :publish
        get :topics
        post :retract
        put :update_topics
        put :update_annotation
        get :publish_notice
      end
    end

    resources :user_roles, only: [:create, :destroy]
    resources :roles
    resources :role_permissions, only: [:create, :destroy]
    resources :permissions
    resources :tasks

    namespace :admin do
      resources :users do
        collection do
          get :admin
        end
        member do
          post :flag
        end
      end
      resources :user_annotations do
        member do
          post :remove
          post :reject
          post :withdraw
          post :postpone
          post :accept
          post :review
        end
      end
      resources :user_statistics do
        collection do
          get :usage_report
        end
      end
     # get 'benutzerstatistik' => 'user_statistics#index', :as => :user_statistics
      resources :imports do
        collection do
          get :for_interview
        end
      end
    end
  end

  get 'photos/src/:name' => 'photos#src'
  get 'photos/thumb/:name' => 'photos#thumb'

end

app/views/admin/_user_annotations_sidebar.html.erb
<div id="userFilters" class="fragmentTitle">
  <h2>Anmerkungen filtern nach:</h2>
  <%= form_tag admin_user_annotations_path, method: :get do %>
    <ul>
      <li>
        <label for="workflow_state">Veröffentlichungsstatus</label>
        <% seloptions = options_for_select((UserAnnotation::PUBLICATION_STATES + ['all']).map{|o| [t(o, :scope => 'user_annotations.workflow_states').capitalize, o]}, :selected => params['workflow_state']) -%>
        <%= select_tag 'workflow_state', seloptions, :class => 'filter' %>
      </li>
      <li>
        <label for="first_name"><%= t(:first_name, :scope => 'devise.registration_fields') %></label>
        <%= text_field_tag 'first_name', params['first_name'], :class => 'filter' %>
      </li>
      <li>
        <label for="last_name"><%= t(:last_name, :scope => 'devise.registration_fields') %></label>
        <%= text_field_tag 'last_name', params['last_name'], :class => 'filter' %>
      </li>
      <li>
        <label for="media_id"><%= t(:media_id, :scope => 'activerecord.attributes.user_annotation') %></label>
        <%= text_field_tag 'media_id', params['media_id'], :class => 'filter' %>
      </li>
      <li id="submit_filters">
        <%= submit_tag "Auswahl aktualisieren" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/admin/_user_sidebar.html.erb
<div id="userFilters" class="fragmentTitle">
  <h2>Benutzer filtern nach:</h2>
  <%= form_tag admin_user_registrations_path, method: :get do %>
    <ul>
      <li>
        <label for="workflow_state">Registrierungsstatus</label>
        <% seloptions = options_for_select((UserRegistration::STATES + ['all']).map{|o| [t(o, :scope => 'devise.workflow_states').capitalize, o]}, :selected => params['workflow_state']) -%>
        <%= select_tag 'workflow_state', seloptions, :class => 'filter' %>
      </li>
      <li>
        <label for="country"><%= t(:country, :scope => 'devise.registration_fields') %></label>
        <% seloptions = country_options_for_select(params['country'], [:de, :at, :ch, :pl, :ru, :cz, :us, :gb, :fr, :nl, :il, :ua, :by]) %>
        <%= select_tag(:country, "<option value='all'>Alle</option>" + seloptions, :class => 'filter') -%>
      </li>
      <% [:job_description, :state, :research_intentions].each do |field| -%>
      <li>
        <label for="<%= field.to_s -%>"><%= t(field, :scope => 'devise.registration_fields') %></label>
        <% seloptions = options_for_select([['Alle', 'all']] + UserRegistration.registration_fields[field][:values].map{|o| [t(o, :scope => ('devise.registration_values.' + field.to_s)), o]}, :selected => params[field]) -%>
        <%= select_tag field, seloptions, :class => 'filter' %>
      </li>
      <% end -%>
      <li>
        <label for="first_name"><%= t(:first_name, :scope => 'devise.registration_fields') %></label>
        <%= text_field_tag 'first_name', params['first_name'], :class => 'filter' %>
      </li>
      <li>
        <label for="last_name"><%= t(:last_name, :scope => 'devise.registration_fields') %></label>
        <%= text_field_tag 'last_name', params['last_name'], :class => 'filter' %>
      </li>
      <li id="submit_filters">
        <%= submit_tag "Auswahl aktualisieren" %>
      </li>
    </ul>
  <% end %>
</div>