config/routes.rb
Rails.application.routes.draw do

  root :to => redirect("/#{Project.default_locale}")
  root to: "home#archive", locale: Project.default_locale.to_sym

  scope "/:locale", :constraints => {:locale => /[a-z]{2}/} do
    devise_for :user_accounts, :controllers => {sessions: 'sessions', passwords: 'passwords'}, skip: [:registrations]
    resources :accounts, only: [:show, :update] do
      member do
        get :confirm_new_email
      end
    end
    resources :user_registrations do
      member do
        post :confirm
        get :activate
        #post :subscribe
        #post :unsubscribe
      end
    end

    localized do
      resources :contributions, only: [:create, :destroy]
      #resources :histories, only: [:create, :update, :destroy]
      resources :biographical_entries, only: [:create, :show, :update]
      resources :photos, only: [:create, :update, :destroy]
      resources :segments, only: [:create, :update, :index, :destroy, :show]
      resources :registry_entries, only: [:create, :show, :update, :index, :destroy] 
      resources :registry_hierarchies, only: [:create, :destroy]
      resources :registry_references, only: [:create, :update, :destroy, :index]
      resources :registry_reference_types, only: [:create, :update, :index, :destroy]
      resources :annotations, only: [:create, :update, :destroy]
      get 'locations', to: 'registry_references#locations', :as => :locations

      resources :people do
        #resources :histories, only: [:create, :update, :destroy]
        resources :biographical_entries, only: [:destroy]
      end

      %w{archive  faq_archive_contents faq_index faq_searching faq_technical map_tutorial}.each do |site|
        get site, to: "home##{site}", as: site
        get '/',  to: "home#archive", as: :home
      end

      #get 'map', to: 'registry_references#map', :as => :public_map
      #get 'mapframe', to: 'registry_references#map_frame', :as => :map_frame

      resources :collections, only: [:show, :index] do
        collection do
          get :countries
        end
      end

      resources :transcripts, only: [:new, :create]
      resources :uploads, only: [:new, :create]

      #post 'upload_transcript', to: 'interviews#upload_transcript', as: :upload_transcript
      #get 'upload_transcript', to: 'interviews#upload_transcript', as: :upload_transcript

      put 'update_speakers/:id', to: 'interviews#update_speakers'

      resources :interviews do
        member do 
          get :doi_contents
          get :headings
          get :initials
          #get :references
          get :ref_tree
        end
        collection do 
          post :dois
          #get :stills
        end
        #resources :registry_entries, only: [:show]
        resources :contributions, only: [:create, :destroy]
        resources :photos, only: [:create, :update, :destroy]
        resources :registry_references, only: [:create, :update, :destroy]
        resources :segments, only: [:create, :update, :index, :destroy]
        resources :tapes do
          collection do
            get :playlist
          end
          member do
            get :transcript
          end
        end
      end

      resources :searches, only: [:new, :facets, :archive, :interview] do
        collection do
          get :facets
          get :archive
          get :export_archive_search
          get :interview
          get :registry_entry
        end
      end
    end

    resources :user_contents do
      collection do
        get :segment_annotation
        post :create_annotation
        post :sort
      end
      member do
        patch :publish
        get :topics
        post :retract
        put :update_topics
        put :update_annotation
        get :publish_notice
      end
    end

    resources :user_roles, only: [:create, :destroy]
    resources :roles
    resources :role_permissions, only: [:create, :destroy]
    resources :permissions
    resources :tasks

    namespace :admin do
      resources :users do
        collection do
          get :admin
        end
        member do
          post :flag
        end
      end
      resources :user_annotations do
        member do
          post :remove
          post :reject
          post :withdraw
          post :postpone
          post :accept
          post :review
        end
      end
      resources :user_statistics do
        collection do
          get :usage_report
        end
      end
     # get 'benutzerstatistik' => 'user_statistics#index', :as => :user_statistics
      resources :imports do
        collection do
          get :for_interview
        end
      end
    end
  end

  get 'photos/src/:name' => 'photos#src'
  get 'photos/thumb/:name' => 'photos#thumb'

end

app/controllers/admin/user_annotations_controller.rb
class Admin::UserAnnotationsController < Admin::BaseController

  before_action :collection, only: [:index]
  before_action :get_object, only: [:show, :update, :accept, :reject]

  def index
    policy_scope(UserAnnotation)
    respond_to do |format|
      format.html 
      format.csv do
        response.headers['Pragma'] = 'no-cache'
        response.headers['Cache-Control'] = 'no-cache, must-revalidate'
        response.headers['Content-Type'] = 'text/comma-separated-values'
        fields = %w(author archive_id media_id timecode_string submitted_at workflow_state description link_url)
        csv = [fields.map{|f| translate_field_or_value(f) }.join("\t")]
        @user_annotations.each do |r|
          r_csv = []
          fields.each do |f|
            r_csv << translate_field_or_value(f, r.send(f.to_sym) || '').gsub(/[,;]+/,'')
          end
          csv << r_csv.join("\t")
        end
        send_data(csv.join("\n"),
                  { :filename => "Nutzeranmerkungen-#{@filters.keys.map{|k| translate_field_or_value(k, @filters[k])}.join("_")}-#{Time.now.strftime('%d.%m.%Y')}.csv",
                    :disposition => 'attachment',
                    :type => 'text/comma-separated-values' })
      end
    end
  end

  def show
  end

  # admin#update may only change description (independent of workflow_state!)
  def update
    @object.update_attribute :description, user_annotation_params['description']
    # also update the published annotation object
    unless @object.annotation.nil?
      @object.annotation.update_attribute :text, user_annotation_params['description']
    end
    respond_to do |format|
      format.html
      format.js 
    end
  end

  def accept
    @object.update_attribute(:description, params['description']) unless params['description'].blank?
    @object.accept!
    @flash = 'Nutzeranmerkung veröffentlicht.'
    render_workflow_change
    expire_annotation_cache
  end

  def reject
    @object.update_attribute(:description, params['description']) unless params['description'].blank?
    @object.reject!
    @flash = 'Nutzeranmerkung abgelehnt.'
    render_workflow_change
  end

  def remove
    @object.update_attribute(:description, params['description']) unless params['description'].blank?
    @object.remove!
    @flash = 'Nutzeranmerkung aus dem Archiv entfernt.'
    render_workflow_change
    expire_annotation_cache
  end

  def withdraw
    @object.update_attribute(:description, params['description']) unless params['description'].blank?
    @object.withdraw!
    @flash = 'Nutzeranmerkung aus der Veröffentlichung zurückgezogen.'
    render_workflow_change
    expire_annotation_cache
  end

  def postpone
    @object.update_attribute(:description, params['description']) unless params['description'].blank?
    @object.postpone!
    @flash = 'Veröffentlichung der Nutzeranmerkung zurückgestellt.'
    render_workflow_change
  end

  def review
    @object.update_attribute(:description, params['description']) unless params['description'].blank?
    @object.review!
    @flash = 'Ablehnung der Nutzeranmerkung aufgehoben.'
    render_workflow_change
  end

  def annotation_filter_params
    [:workflow_state, :media_id, :first_name, :last_name, :format]
  end
  helper_method :annotation_filter_params

  private

  def collection
    @filters = {}
    conditionals = []
    condition_args = []
    # workflow state
    @filters['workflow_state'] = params['workflow_state'] || 'proposed'
    unless @filters['workflow_state'].blank? || @filters['workflow_state'] == 'all'
      conditionals << "(workflow_state = '#{@filters['workflow_state']}'" + (@filters['workflow_state'] == "unchecked" ? " OR workflow_state IS NULL)" : ")")
    end
    @filters['workflow_state']
    # user name
    %w(last_name first_name).each do |name_part|
      @filters[name_part] = params[name_part]
      unless @filters[name_part].blank?
        conditionals << "users.#{name_part} LIKE ?"
        condition_args << @filters[name_part] + '%'
      end
    end
    @filters['media_id'] = params['media_id']
    unless @filters['media_id'].blank?
      conditionals << "properties LIKE ?"
      condition_args << "%media_id: #{ActiveRecord::Base.connection.quote(@filters['media_id'].upcase)[1..-2]}%"
    end
    @filters = @filters.delete_if{|k,v| v.blank? || v == 'all' }
    # never show private annotations
    conditionals << "workflow_state != ?"
    condition_args << "private"
    conditions = [ conditionals.join(' AND ') ] + condition_args
    conditions = conditions.first if conditions.length == 1
    @user_annotations = UserAnnotation.joins(:user).where(conditions).order("submitted_at DESC")
  end

  def get_object
    @object = UserAnnotation.find(params[:id])
    authorize @object
  end

  def render_workflow_change
    respond_to do |format|
      format.html do
        flash[:alert] = @flash
        redirect_to admin_user_annotations_path(params)
      end
      format.js do
        render :update
      end
    end
  end

  def expire_annotation_cache
    expire_fragment(fragment_cache_key("annotations_#{@object.archive_id}"))
  end

  def translate_field_or_value(field, value=nil)
    unless value.nil?
      if value.is_a?(Time)
        return value.strftime('%d.%m.%Y %H:%M Uhr')
      end
      if value.blank?
        return ''
      end
      if value == true
        return 'ja'
      end
      value.strip! if value.is_a?(String)
      scope = case field
                when 'author', 'media_id', 'description', 'archive_id', 'timecode_string'
                  return value
                when 'reference'
                  return value.to_s
                when 'link_url'
                  return File.join([request.host_with_port, ApplicationController.relative_url_root, value].compact)
                when 'workflow_state'
                  'user_annotations.workflow_states'
                else
                  'activerecord.attributes.user_annotation.' + field.to_s
              end
      t(value, :scope => scope, :locale => :de)
    else
      t(field, :scope => 'activerecord.attributes.user_annotation', :locale => :de)
    end
  end

  def user_annotation_params
    params.require(:user_annotation).permit(:description)
  end

end

app/helpers/admin/user_annotations_helper.rb
module Admin::UserAnnotationsHelper

  def annotation_inline_edit_for(user_annotation, options={})
    id = "user_annotation_#{user_annotation.id}_description"
    form_id = id + '_form'
    actions_id = id + '_actions'
    update_path = admin_user_annotation_path(user_annotation)
    form_options = options.merge({
                                     id: form_id,
                                     method: :put,
                                     remote: true,
                                     class: 'inline'
                                 })
    html = content_tag(:div, options.merge({:id => form_id, :class => 'inline-editor'})) do
      form_tag(update_path, form_options) do
        form_html = text_area_tag(user_annotation, user_annotation.description, :id => id, :name => "user_annotation[description]", :class => 'editor')
        buttons_html = submit_tag("", :id => "#{id}_update", :class => "update", data: {title: t(:update, :scope => 'user_interface.actions')})
        buttons_html += "<input type='reset' id='#{id}_reset' name='#{id}_reset' title='#{t(:reset, :scope => 'user_interface.actions')}' class='reset' />".html_safe
        spinner_html = image_tag(image_path('/images/spinner.gif'), :id => "#{id}_spinner", :style => 'display:none;')
        form_html + content_tag(:span, buttons_html, :id => actions_id, :style => 'display: none;') + spinner_html
      end
    end
    html
  end

end

app/views/admin/user_annotations/_user_annotation.html.erb
<li id="user_annotation_<%= user_annotation.id -%>" class="user_annotation<%= (defined?(container_open) && container_open) ? '' : ' closed' -%>">
        <span class="data author" style="font-size: 90%; position: relative;">
          <%# contents are in reverse display order to enable sorting by name %>
          <span style="padding-left: 18px; margin-top: 1.8em;">
            <%= link_to "&raquo;&nbsp;#{user_annotation.author}".html_safe, edit_admin_user_registration_path(user_annotation.user.user_registration), :style => "color: #990000;", :target => '_blank' %>
          </span>
          <span style="position: absolute; top: 0; left: 0;">
            <%= link_to "Anmerkung vom #{formatted_time(user_annotation.created_at).sub(/\s+\d+:\d+\s+Uhr/,'')}", "#", close: "#user_annotation_#{user_annotation.id}", :class => 'more', :title => "Details" %>
          </span>
        </span>
        <span class="segment">
          <%= link_to_segment user_annotation.reference, '', false, false, {:link_text => content_tag(:span, "<span style='font-weight: bold; width: 100%;'>#{user_annotation.reference.interview.archive_id}</span>#{user_annotation.reference.interview.short_title(I18n.locale)}<br/>#{user_annotation.timecode_string(I18n.locale)}".html_safe ), :target => '_blank'} %>
        </span>
        <span class="data status">
          <%= t(user_annotation.workflow_state, :scope => 'user_annotations.workflow_states') -%>
        </span>
        <span class="data submission_date">
          <span style="display: none;">
            <%= user_annotation.submitted_at -%>
          </span>
          <%= formatted_time user_annotation.submitted_at, '<span style="font-weight: normal !important; width: 132px;">? (Feb 2013 o. früher)</span>'.html_safe -%>
        </span>

  <div id="annotation_info_<%= user_annotation.id -%>" class="details">
    <%= annotation_inline_edit_for(user_annotation, :width => '220px;', :class => 'textbox') -%>
    <div class="actions">
      <% if %(proposed postponed).include?(user_annotation.workflow_state) -%>
          <%= workflow_action_for(:user_annotations, :accept, user_annotation, false) %>
      <% end -%>
      <% if user_annotation.proposed? -%>
          <%= workflow_action_for(:user_annotations, :postpone, user_annotation, true) %>
      <% end -%>
      <% if user_annotation.rejected? -%>
          <%= workflow_action_for(:user_annotations, :review, user_annotation, false) %>
      <% end -%>
      <% if user_annotation.shared? -%>
          <%= workflow_action_for(:user_annotations, :withdraw, user_annotation, true) %>
          <%= workflow_action_for(:user_annotations, :remove, user_annotation, true) %>
      <% end -%>
      <% if %(proposed postponed).include?(user_annotation.workflow_state) -%>
          <%= workflow_action_for(:user_annotations, :reject, user_annotation, true) %>
      <% end -%>
    </div>
  </div>

</li>

app/views/admin/user_annotations/index.html.erb
<h1><%= @user_annotations.size == 0 ? 'Keine' : @user_annotations.size -%> Nutzeranmerkungen (<%= t(params['workflow_state'] || 'proposed', :scope => 'user_annotations.workflow_states') %>)</h1>

<h4><%= link_to "&raquo;&nbsp;Tabellendownload (als .CSV)".html_safe, admin_user_annotations_path(params.permit(annotation_filter_params).merge(format: :csv)) %><h4>

<div id="user_annotations">
  <div id="sorting_controls">
    <span id="id_sort" class="sort" data-sort="author">sortieren nach Autor</span>
    <span id="status_sort" class="sort" data-sort="status" style="float: right;">sortieren nach Stand</span>
    <span id="submission_sort" class="sort" data-sort="submission_date">sortieren nach Datum</span>
    <div class="labels">
        <span class="author">
           Autor
        </span>
        <span class="segment" style="margin-left: -6px;">
          Segment / Zeitzeuge
        </span>
        <span class="status">
          Status
        </span>
        <span class="submission_date" style="text-align: left; padding-right: 10px;">
          Einreichung am
        </span>
    </div>
  </div>
  <ul class="list">
    <%= render :partial => 'user_annotation', :collection => @user_annotations -%>
  </ul>
</div>

<%= javascript_tag do -%>
    var annotationslist = new List('user_annotations', { valueNames: ['author', 'submission_date', 'status'], page: 600 });
<% end -%>

<% unless request.xhr? -%>
    <% content_for :title do -%>
        Nutzeranmerkungen
    <% end -%>
    <% content_for :sidebar do -%>
        <%= render :partial => '/admin/user_annotations_sidebar.html.erb' -%>
    <% end -%>
<% end -%>

app/views/admin/user_annotations/update.js.erb
jQuery("#user_annotation_<%= @object.id %>").replaceWith('<%= escape_javascript(render partial: 'user_annotation', object: @object, container_open: true) %>')
jQuery('#shades').hide();