config/routes.rb
Rails.application.routes.draw do

  root :to => redirect("/#{Project.default_locale}")
  root to: "home#archive", locale: Project.default_locale.to_sym

  scope "/:locale", :constraints => {:locale => /[a-z]{2}/} do
    devise_for :user_accounts, :controllers => {sessions: 'sessions', passwords: 'passwords'}, skip: [:registrations]
    resources :accounts, only: [:show, :update] do
      member do
        get :confirm_new_email
      end
    end
    resources :user_registrations do
      member do
        post :confirm
        get :activate
        #post :subscribe
        #post :unsubscribe
      end
    end

    localized do
      resources :contributions, only: [:create, :destroy]
      #resources :histories, only: [:create, :update, :destroy]
      resources :biographical_entries, only: [:create, :show, :update]
      resources :photos, only: [:create, :update, :destroy]
      resources :segments, only: [:create, :update, :index, :destroy, :show]
      resources :registry_entries, only: [:create, :show, :update, :index, :destroy] 
      resources :registry_hierarchies, only: [:create, :destroy]
      resources :registry_references, only: [:create, :update, :destroy, :index]
      resources :registry_reference_types, only: [:create, :update, :index, :destroy]
      resources :annotations, only: [:create, :update, :destroy]
      get 'locations', to: 'registry_references#locations', :as => :locations

      resources :people do
        #resources :histories, only: [:create, :update, :destroy]
        resources :biographical_entries, only: [:destroy]
      end

      %w{archive  faq_archive_contents faq_index faq_searching faq_technical map_tutorial}.each do |site|
        get site, to: "home##{site}", as: site
        get '/',  to: "home#archive", as: :home
      end

      #get 'map', to: 'registry_references#map', :as => :public_map
      #get 'mapframe', to: 'registry_references#map_frame', :as => :map_frame

      resources :collections, only: [:show, :index] do
        collection do
          get :countries
        end
      end

      resources :transcripts, only: [:new, :create]
      resources :uploads, only: [:new, :create]

      #post 'upload_transcript', to: 'interviews#upload_transcript', as: :upload_transcript
      #get 'upload_transcript', to: 'interviews#upload_transcript', as: :upload_transcript

      put 'update_speakers/:id', to: 'interviews#update_speakers'

      resources :interviews do
        member do 
          get :doi_contents
          get :headings
          get :initials
          #get :references
          get :ref_tree
        end
        collection do 
          post :dois
          #get :stills
        end
        #resources :registry_entries, only: [:show]
        resources :contributions, only: [:create, :destroy]
        resources :photos, only: [:create, :update, :destroy]
        resources :registry_references, only: [:create, :update, :destroy]
        resources :segments, only: [:create, :update, :index, :destroy]
        resources :tapes do
          collection do
            get :playlist
          end
          member do
            get :transcript
          end
        end
      end

      resources :searches, only: [:new, :facets, :archive, :interview] do
        collection do
          get :facets
          get :archive
          get :export_archive_search
          get :interview
          get :registry_entry
        end
      end
    end

    resources :user_contents do
      collection do
        get :segment_annotation
        post :create_annotation
        post :sort
      end
      member do
        patch :publish
        get :topics
        post :retract
        put :update_topics
        put :update_annotation
        get :publish_notice
      end
    end

    resources :user_roles, only: [:create, :destroy]
    resources :roles
    resources :role_permissions, only: [:create, :destroy]
    resources :permissions
    resources :tasks

    namespace :admin do
      resources :users do
        collection do
          get :admin
        end
        member do
          post :flag
        end
      end
      resources :user_annotations do
        member do
          post :remove
          post :reject
          post :withdraw
          post :postpone
          post :accept
          post :review
        end
      end
      resources :user_statistics do
        collection do
          get :usage_report
        end
      end
     # get 'benutzerstatistik' => 'user_statistics#index', :as => :user_statistics
      resources :imports do
        collection do
          get :for_interview
        end
      end
    end
  end

  get 'photos/src/:name' => 'photos#src'
  get 'photos/thumb/:name' => 'photos#thumb'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout 'responsive'

  skip_before_action :authenticate_user_account!
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def map_tutorial
    render layout: false
  end

  def archive
    respond_to do |format|
      format.html do
        render :template => '/react/app.html'
      end
      format.json do
        locales = Project.available_locales.reject{|i| i == 'alias'}
        json = Rails.cache.fetch("#{Project.cache_key_prefix}-static-content") do 
          {
            external_links: Project.external_links,
            translations: translations,
            country_keys: locales.inject({}) do |mem, locale|
              mem[locale] = ISO3166::Country.translations(locale).sort_by{|key, value| value}.to_h.keys
              mem
            end,
            collections: Collection.all.map{|c| {value: c.id, name: c.localized_hash}}, 
            contribution_types: Project.contribution_types,
            registry_entry_search_facets: Project.registry_entry_search_facets.map{|facet| {id: RegistryEntry.find_by_entry_code(facet['id']).id, display_on_landing_page: facet['display_on_landing_page']}},
            person_properties_registry_reference_type: Project.person_properties_registry_reference_type.inject({}){|mem, facet| mem[facet['id']] = RegistryReferenceTypeSerializer.new(RegistryReferenceType.find_by_code(facet['id'])).as_json; mem},
            languages: Language.all.map{|c| {value: c.id.to_s, name: c.localized_hash, locale: ISO_639.find(c.code.split(/[\/-]/)[0]).alpha2}}, 
            upload_types: Project.upload_types,
            project: Project.name.to_s,
            project_name: Project.project_name,
            project_domain: Project.project_domain,
            project_doi: Project.project_doi,
            archive_domain: Project.archive_domain,
            locales: Project.available_locales,
            media_streams: Project.media_streams,
            hidden_registry_entry_ids: Project.hidden_registry_entry_ids,
          }
        end
        home_content = {}
        locales.each do |i|
          I18n.locale = i
          template = "/home/home.#{i}.html+#{Project.name == 'empty' ? 'zwar' : Project.name}"
          home_content[i] = render_to_string(template: template, layout: false)
        end
        json[:home_content] = home_content
        render plain: json.to_json
      end
    end
  end

  def faq_archive_contents
  end

  def faq_index
  end

  def faq_searching
  end

  def faq_technical
  end

  def map_tutorial
  end

  private

  def translations
    I18n.available_locales.inject({}) do |mem, locale|
      mem[locale] = instance_variable_get("@#{locale}") || 
        instance_variable_set("@#{locale}", 
                              YAML.load_file(File.join(Rails.root, "config/locales/#{locale}.yml"))[locale.to_s].deep_merge(
                                YAML.load_file(File.join(Rails.root, "config/locales/devise.#{locale}.yml"))[locale.to_s]).merge(
                                  countries: ISO3166::Country.translations(locale)
                                )
                             )
      mem
    end
  end

end

app/views/home/archive.en.html+mog.erb
<h1>The Interview Archive “Forced Labor 1939-1945” </h1>

<%= render 'teaser' %>

<p></p>

<p>The interview archive “Forced Labor 1939-1945” contains interviews with nearly 600 former
  forced laborers from 26 countries. The collection is made up of various subsets, which were
  compiled worldwide between the years 2005 and 2006 and financed by the Foundation
  “Remembrance, Responsibility and Future”. The digital archive preserves these testimonies
  for the future and makes them available for educational and research purposes.</p>

<% if current_user_account.nil? %>
<p style="font-weight: bold">
  In order to protect privacy rights you must be <%= link_to 'logged in', new_user_account_session_path(:en) %> and agree to the
  <%= external_link('devise.registration_fields.tos_agreement', :nutzungsbedingungen) %> as well as
  the <%= external_link('devise.registration_fields.priv_agreement', :datenschutzbestimmungen) %>
  before being granted access to the archive.
</p>
<% else %>
<br/>
<p>
  As a registered user you are given access to all interviews in full length that
  we have been given permission to publicize on the web under our
  <%= external_link('devise.registration_fields.tos_agreement', :nutzungsbedingungen) %> and
  <%= external_link('devise.registration_fields.priv_agreement', :datenschutzbestimmungen) %>.
</p>
<% end %>

<br style="clear: both;"/>

<div class="contentImagesLeft">
  <div class="contentImage100">
    <a href="#">
      <img src="<%= image_path("#{Project.name}/teaser/categories.png") %>" alt="Categories"/>
    </a>
  </div>
</div>
<h3 style="margin-top: 8px;">Category Search</h3>
<p>
  Content categories in the search menu bar on the right give an overview of the classification system of the archive and provide thematically structured access.
  <br/>
    <%= link_to 'description of categories »',
                faq_searching_path(anchor: 'recherchemoeglichkeiten'),
                title: 'Which research features are available?' %>
    <br/>
</p>
<br style="clear: both;"/>

<div class="contentImagesLeft">
  <div class="contentImage100">
    <a href="#">
      <img src="<%= image_path("#{Project.name}/teaser/fulltext.png") %>" alt="Fulltext Search"/>
    </a>
  </div>
</div>
<h3 style="margin-top: 8px;">Fulltext Search</h3>
<p>
  Fulltext search via the search field on the right enables an intuitive access via search terms which specifically suit your research motivation.
  <br/>
    <%= link_to 'explanation of fulltext search »',
                faq_searching_path(anchor: 'suche-allgemein'),
                title: 'How should I use full text search?' %>
    <br/>
</p>
<br style="clear: both;"/>

<div class="contentImagesLeft">
  <div class="contentImage100">
    <a href="<%= public_map_path -%>">
      <img src="<%= image_path("#{Project.name}/teaser/karte.png") %>" alt="Map"/>
    </a>
  </div>
</div>
<h3 style="margin-top: 8px;">Map</h3>
<p>
  An interactive map shows sites of biographical relevance to the interviewees: place of birth, deportation, camps, companies and prisons, places of residence after 1945.
  <br/>
    <%= link_to 'interactive map »', public_map_path, title: 'interactive Map' %>
    <br/>
</p>
<br style="clear: both;"/>

<div class="contentImagesLeft">
  <div class="contentImage100">
    <a href="<%= collections_path -%>">
      <img src="<%= image_path("#{Project.name}/teaser/collections.png") %>" alt="Collections"/>
    </a>
  </div>
</div>
<h3 style="margin-top: 8px;">Overview of Collections</h3>
<p>
  The overview map of the project's collections illustrate the provenance of the archive and provide a regional access.
  <br/>
    <%= link_to 'overview map of collections »', collections_path, :title => 'geographic distribution of interview collections' %>
    <br/>
</p>

<hr style="clear: both;"/>
<h2 class="clear">Multilingual Archive</h2>
<p>
    The archive, with interviews conducted in 25 languages, is completely available in German. The user
    interface and data about the people and the interviews are also available in English and Russian.
</p>
<p>
    The table of contents, captions, short biographies and editorial comments are available in Russian
    for the Russian interviews, and in English for the English interviews. Interviews in other languages
    are displayed in German, even if you have selected the Russian or English archive version.
</p>
<h2 class="clear">FAQs</h2>
<p>
    Please see the <%= link_to t(:faq), faq_index_path, title: 'Q&A concerning archive features.' %>
    for technical advice or if you have any questions about the archive contents or using the archive.
    If your questions cannot be answered here, please  contact: <a href="mailto:mail@zwangsarbeit-archiv.de" target="_blank" title="Contact Email">mail@zwangsarbeit-archiv.de</a>
</p>

app/views/home/archive.html.erb
        <h1>Das Online-Archiv "Zwangsarbeit 1939-1945"</h1>

        <div class="contentImagesLeft">
          <div class="contentImage150">
            <img src="<%= image_path '180_DolezalMiroslavPhot09_150.jpg' %>" alt="Doležal, Miroslav" title="" />
            <h6>Doležal, Miroslav</h6>
          </div>
          <div class="contentImage150">
            <img src="<%= image_path 'ZA007_03_150.jpg' %>" alt="Poleschtschuk, Anna Iwanowna" title="" />
            <h6>Poleschtschuk, Anna Iwanowna</h6>
          </div>
        </div>

        <p> </p>

        <p>Das Online-Archiv &quot;Zwangsarbeit 1939-1945&quot; beinhaltet Zeitzeugen-Interviews von knapp 600 ehemaligen Zwangsarbeiterinnen und Zwangsarbeitern aus 26 Ländern, die während der Zeit des Nationalsozialismus Zwangsarbeit geleistet haben. Das Archiv setzt sich aus unterschiedlichen Teilsammlungen zusammen. Diese wurden, finanziert durch die Stiftung &quot;Erinnerung, Verantwortung und Zukunft&quot;, in den Jahren 2005-2006 von verschiedenen Institutionen weltweit erstellt. Das digitale Archiv bewahrt diese Zeitzeugnisse für die Zukunft und stellt sie für Bildung und Wissenschaft zur Verfügung.</p>

        <h2> </h2>
        <h2>Recherchemöglichkeiten</h2>
        <p>Der Einstieg in eine Recherche in dem Archiv ist über die folgenden drei Wege möglich:<br /><br /></p>
        <hr />
        <p>Inhaltliche Kategorien (rechts in der Navigation) für einen thematisch strukturierten Zugang<br /><strong><a href="hilfe/suche/recherchemoeglichkeiten.html" title="Welche Recherchemöglichkeiten gibt es?">mehr zu den Kategorien »</a><br /></strong></p>
        <hr />
        <p>Karte der geographischen Verteilung der Teilsammlungen für einen regionalen Zugang<br /><strong><a href="/collections" title="Karte">Karte »</a><br /><a href="../sammlung/teilsammlungen/index.html" target="_blank" title="Teilsammlungen">mehr zu den Teilsammlungen »</a><br /></strong></p>
        <hr />
        <p>Volltextsuche für einen breiten und intuitiven Zugang<br /><strong><a href="suche/index.html" title="Suche in den Interviews">Volltextsuche »</a><br /><a href="hilfe/suche/suche-allgemein.html" title="Wie kann ich die Volltextsuche nutzen?">mehr zur Suche »</a></strong></p>
        <hr />
        <h2 class="clear">Fragen und Antworten</h2>
        <p>Über die <a href="hilfe/index.html" title="Hilfe">Hilfe</a> auf dieser Seite finden Sie inhaltliche oder technische Hinweise zur Nutzung des Archivs. Sollten Ihre Fragen dort nicht beantwortet werden, schreiben Sie uns bitte eine E-Mail an: <a href="mailto:mail@zwangsarbeit-archiv.de" target="_blank" title="Kontakt">mail@zwangsarbeit-archiv.de</a></p>

app/views/home/archive.ru.html+zwar.erb
<h1>Архив интервью "Принудительный труд 1939-1945"</h1>

<%= render 'teaser' %>

<p></p>

<p>
  Архив интервью &quot;Принудительный труд 1939-1945&quot; содержит интервью почти с 600 бывшими невольниками и невольницами труда из 26 стран.
  Архив состоит из нескольких частей, составленных в 2005 - 2006гг. различными проектными группами  по всему миру при финансовой поддержке фонда &quot;Память, ответственность и будущее&quot;.
  Цифровой архив хранит свидетельства времени для будущих поколений и обеспечивает их использование в сфере образования и науки
</p>

<% if current_user_account.nil? %>
  <p style="font-weight: bold;">
    В целях защиты прав личности для использования архива "Принудительный труд 1939-1945" Вы должны <%= link_to 'войти в систему', new_user_account_session_path %> и принять как <%= external_link('devise.registration_fields.tos_agreement', :nutzungsbedingungen) %>, так и <%= external_link('devise.registration_fields.priv_agreement', :datenschutzbestimmungen) %>.
  </p>
<% else %>
  <br/>
  <p>
    B качестве зарегистрированного пользователя Вы получите доступ ко всем интервью, представленным в полном объеме в интернет, при условии, что будут соблюдены <%= external_link('devise.registration_fields.tos_agreement', :nutzungsbedingungen) %> и
    <%= external_link('devise.registration_fields.priv_agreement', :datenschutzbestimmungen) %>.
  </p>
<% end %>

<br style="clear: both;"/>

<div class="contentImagesLeft">
  <div class="contentImage100">
    <a href="#">
      <img src="<%= image_path("#{Project.name}/teaser/categories_ru.png") %>" alt="Категории"/>
    </a>
  </div>
</div>
<h3 style="margin-top: 8px;">Поиск по категориям</h3>
<p>
  Категории в поисковой панели в правом краю экрана, отображающие содержание, позволяют ознакомиться с систематикой архива и служат тематически структурированному доступу в архив.
  <br/>
    <%= link_to 'Описание категорий »',
                faq_searching_path(anchor: 'recherchemoeglichkeiten'),
                title: 'Какие возможности поиска существуют?' %>
    <br/>
</p>
<br style="clear: both;"/>

<div class="contentImagesLeft">
  <div class="contentImage100">
    <a href="#">
      <img src="<%= image_path("#{Project.name}/teaser/fulltext_ru.png") %>" alt="Полнотекстовый поиск"/>
    </a>
  </div>
</div>
<h3 style="margin-top: 8px;">Полнотекстовый поиск</h3>
<p>
  Полнотекстовый поиск посредством поисковой панели справа предоставляет возможность интуитивного доступа к архиву с помощью ключевых понятий, чётко соответствующих цели Ваших изысканий.
  <br/>
    <%= link_to 'Описание полнотекстового поиска »',
                faq_searching_path(anchor: 'suche-allgemein'),
                title: 'Как я могу использовать полнотекстовый поиск?' %>
    <br/>
</p>
<br style="clear: both;"/>

<div class="contentImagesLeft">
  <div class="contentImage100">
    <a href="<%= public_map_path -%>">
      <img src="<%= image_path("#{Project.name}/teaser/karte.png") %>" alt="Карта"/>
    </a>
  </div>
</div>
<h3 style="margin-top: 8px;">Поиск по карте</h3>
<p>
  С помощью интерактивной карты предоставляется возможность поиска информации о биографических этапах интервьюируемых: место рождения, место депортации, лагерь, фирмы и места заключения, места жительства с 1945 г.
  <br/>
    <%= link_to 'К поиску по карте »', public_map_path, title: 'Поиск по карте' %>
    <br/>
</p>
<br style="clear: both;"/>

<div class="contentImagesLeft">
  <div class="contentImage100">
    <a href="<%= collections_path -%>">
      <img src="<%= image_path("#{Project.name}/teaser/collections.png") %>" alt="Частичные собрания"/>
    </a>
  </div>
</div>
<h3 style="margin-top: 8px;">Обзор частичных собраний</h3>
<p>
  Обзор географического распределения частичных собраний позволяет ознакомиться с историей возникновения архива и обеспечивает региональный подход.
  <br/>
    <%= link_to 'К карте частичных собраний »', collections_path, :title => 'Географическое распределение частичных собраний' %>
    <br/>
</p>

<hr style="clear: both;"/>
<h2 class="clear">Многоязычный архив</h2>
<p>
    Архив интервью, состоявшихся на 25 языках, представлен в полном объёме на немецком языке. Интерфейс,
    а также биографические данные и интервью переведены на английский и русский языки.
</p>
<p>
    Содержание, подписи под фотографиями и картинками, краткие биографии и редакционные примечания доступны
    для русскоязычных и англоязычных пользователей на названных языках, но в интервью на других языках –
    олько по-немецки, даже если Вы выбрали русскую или английскую версию архива.
</p>
<h2 class="clear">Вопросы и ответы</h2>
<p>
  В разделе <%= link_to t(:faq), faq_index_path, title: 'Вопросы и ответы, касающиеся использования архива' %>
  Вы найдёте ответы на вопросы, касающиеся технической стороны архива или его содержания. Если Ваши вопросы всё-таки останутся без ответа, напишите нам письмо на следующий электронный адрес:
  <a href="mailto:mail@zwangsarbeit-archiv.de" target="_blank" title="Контакт">
    mail@zwangsarbeit-archiv.de
  </a>
</p>

app/views/home/home.el.html+eog.slim
h1 Erinnerungen an die Okkupation in Griechenland
p.lead
  | Über die deutsche Besatzung Griechenlands ist in Deutschland sehr wenig bekannt. In Griechenland sind die Okkupation und die begangenen Verbrechen immer noch sehr präsent.
p
  |Im Projekt "Erinnerungen an die Okkupation in Griechenland" werden mindestens 70 lebensgeschichtliche Video-Interviews mit griechischen Zeitzeuginnen und Zeugen aufgenommen.
p
  |Ihre Erinnerungen an die Besatzung werden für die Zukunft bewahrt und für das Internet aufbereitet.


p
  |Informationen zum Projekt

p
  |Film zum Projekt

app/views/home/home.ru.html+hagen.slim
.home-text
  h1 Архив интервью "Принудительный труд 1939-1945"

  - @interview = Interview.random_featured
  div style=("float: left; margin: 0 15px 0 0;")
    a href=("#{interview_path(:id => @interview.archive_id)}") 
      img alt="#{@interview.short_title(I18n.locale)}" height="150" src=("#{ "https://medien.cedis.fu-berlin.de/zwar/stills/#{@interview.archive_id}_still_original.JPG"}") title="" width="200" /
      h6
        = @interview.short_title(I18n.locale)
        br/
        = t(@interview.video? ? 'media.video_interview' : 'media.audio_interview')
        | , #{@interview.language.to_s}

  p
    | Архив интервью "Принудительный труд 1939-1945" содержит интервью почти с 600 бывшими невольниками
      и невольницами труда из 26 стран. Архив состоит из нескольких частей, составленных в 2005 - 2006гг.
      различными проектными группами по всему миру при финансовой поддержке фонда "Память, ответственность
      и будущее". Цифровой архив хранит свидетельства времени для будущих поколений и обеспечивает их
      использование в сфере образования и науки 
  p
    | В целях защиты прав личности для использования архива "Принудительный труд 1939-1945" Вы должны
      войти в систему и принять как Правила пользования сайтом, так и Положения о защите персональных данных.  

  p
    | B качестве зарегистрированного пользователя Вы получите доступ ко всем интервью, представленным
      в полном объеме в интернет, при условии, что будут соблюдены Правила пользования сайтом и Положения
      о защите персональных данных. 

app/views/home/map_tutorial.ru.html+zwar.erb
<ul style="float: right;">
    <!-- Slide 1 //-->
    <li class="hint slide-1"><h3 style="margin: 0;">Инструкция по использованию карты:<br/>Часть 1 - Фильтр<a href="#" onclick="new Effect.Fade('initial_map_tutorial');" class="window-close"><%= t(:close) -%></a></h3></li>
    <li class="hint slide-1">
      <p>Обзорная карта с указаниями местонахождения подневольных рабочих содержит различные сведения биографической важности. Для большей наглядности с помощью так называемых фильтров можно в любое время выбрать, какие сведения должны быть отображены, а какие нет.</p>
    </li>
    <li class="hint slide-1"><p>Пожалуйста, выберите вид сведений, которые Вас интересуют, и пронаблюдайте отображение местонахождений на карте:</p></li>
    <li class="map_filter_off forced_labor_location slide-1"><span><%= t(:forced_labor_locations, :scope => 'map.labels') -%></span></li>
    <li class="map_filter_off forced_labor_camp slide-1"><span><%= t(:camps, :scope => 'map.labels') -%></span>
    <li class="map_filter_off forced_labor_company slide-1"><span><%= t(:companies, :scope => 'map.labels') -%></span></li>
    <li class="map_filter_off deportation_location slide-1"><span><%= t(:deportations, :scope => 'map.labels') -%></span></li>
    <li class="map_filter_off birth_location slide-1"><span><%= t(:places_of_birth, :scope => 'map.labels') -%></span></li>
    <li class="map_filter_off return_location slide-1"><span><%= t(:postwar_residences, :scope => 'map.labels') -%></span></li>
    <li class="map_filter_off postwar_camp slide-1"><span><%= t(:postwar_camps, :scope => 'map.labels') -%></span></li>
    <li class="map_filter_off home_location slide-1"><span><%= t(:home_locations, :scope => 'map.labels') -%></span></li>
    <li class="map_filter_off interview slide-1"><span><%= t(:mentions, :scope => 'map.labels') -%></span></li>
    <li class="hint slide-1">
      <p>Ваши настройки будут сохранены в браузере и использованы автоматически при следующем просмотре карты.</p>
    </li>

    <!-- Slide 2 //-->
    <li class="hint slide-2"><h3 style="margin: 0;">Инструкция по использованию карты:<br/>Часть 2 - Разбивка на группы<a href="#" onclick="new Effect.Fade('initial_map_tutorial');" class="window-close"><%= t(:close) -%></a></h3></li>
    <li class="hint slide-2">
      <p>Для ясности при низкой степени увеличения указания местонахождения могут быть скомбинированы по странам и регионам. Данную функцию можно в любое время деактивировать посредством отмены пункта "Разбивка на группы..." в фильтрах.</p>
    </li>
    <li class="cluster_toggle clusters-off slide-2" onclick="toggleClusters();"><span><%= t(:grouping_label, :scope => 'map.legend') -%></span></li>
    <li class="hint slide-2">
      <p>Количество охваченных местонахождений сигнализируется с помощью размера кружков и отображённых чисел. Нажатие на центр кружка или сгруппированных данных приведёт на следующий детальный уровень информации.</p>
    </li>
    <li class="hint slide-2">
      <p>Фильтрами и возможностью разбивки на группы Вы можете воспользоваться в любое время.<img class="imageRight" src="<%= image_path('map/tut_legend_ru.png') -%>"/> Для отображения возможностей фильтра Вам нужно только нажать на кнопку "<%= t(:tabname, :scope => 'map.legend') -%>" вверху справа. Нажав на крестик вверху справа в легенде, Вы можете снова скрыть фильтры.</p>
    </li>

    <!-- Slide 3 //-->
    <li class="hint slide-3"><h3 style="margin: 0;">Инструкция по использованию карты:<br/>Часть 3 - Интервью<a href="#" onclick="new Effect.Fade('initial_map_tutorial');" class="window-close"><%= t(:close) -%></a></h3></li>
    <li class="hint slide-3">
      <p>При выборе места на карте Вы получите дальнейшую информацию, касающуюся данного местонахождения и соответствующих интервью.</p>
    </li>
    <li class="hint slide-3">
      <img src="<%= image_path('map/tut_interview_ru.png') -%>" alt="Информация, касающаяся интервью"/>
    </li>
    <li class="hint slide-3">Данные, касающиеся интервью, приведут Вас напрямую к соответствующим фрагментам в интервью при условии, что Вы зарегистрированы в архиве.</li>
    <li class="hint slide-3">Если Вы ещё не зарегистрированы в архиве, Вы можете заполнить наш <%= link_to 'Формуляр для использования архива и зарегистрироваться', new_user_account_registration_path, :target => '_blank' -%>.</li>

    <!-- Slide Actions //-->
    <li class="hint links">
      <p><a class="back not-slide-1" href="#" onclick="adjustSlideNum(-1);">&laquo;&nbsp;назад</a><span class="not-slide-1">&nbsp;или&nbsp;</span><a class="forward not-slide-3" href="#" onclick="adjustSlideNum(1);">далее&nbsp;&raquo;</a><a class="finish slide-3" href="#" onclick="endTutorial();">&raquo;&nbsp;закрыть инструкцию</a></p>
    </li>
</ul>