config/routes.rb
Rails.application.routes.draw do

  root :to => redirect("/#{Project.default_locale}")
  root to: "home#archive", locale: Project.default_locale.to_sym

  scope "/:locale", :constraints => {:locale => /[a-z]{2}/} do
    devise_for :user_accounts, :controllers => {sessions: 'sessions', passwords: 'passwords'}, skip: [:registrations]
    resources :accounts, only: [:show, :update] do
      member do
        get :confirm_new_email
      end
    end
    resources :user_registrations do
      member do
        post :confirm
        get :activate
        #post :subscribe
        #post :unsubscribe
      end
    end

    localized do
      resources :contributions, only: [:create, :destroy]
      #resources :histories, only: [:create, :update, :destroy]
      resources :biographical_entries, only: [:create, :show, :update]
      resources :photos, only: [:create, :update, :destroy]
      resources :segments, only: [:create, :update, :index, :destroy, :show]
      resources :registry_entries, only: [:create, :show, :update, :index, :destroy] 
      resources :registry_hierarchies, only: [:create, :destroy]
      resources :registry_references, only: [:create, :update, :destroy, :index]
      resources :registry_reference_types, only: [:create, :update, :index, :destroy]
      resources :annotations, only: [:create, :update, :destroy]
      get 'locations', to: 'registry_references#locations', :as => :locations

      resources :people do
        #resources :histories, only: [:create, :update, :destroy]
        resources :biographical_entries, only: [:destroy]
      end

      %w{archive  faq_archive_contents faq_index faq_searching faq_technical map_tutorial}.each do |site|
        get site, to: "home##{site}", as: site
        get '/',  to: "home#archive", as: :home
      end

      #get 'map', to: 'registry_references#map', :as => :public_map
      #get 'mapframe', to: 'registry_references#map_frame', :as => :map_frame

      resources :collections, only: [:show, :index] do
        collection do
          get :countries
        end
      end

      resources :transcripts, only: [:new, :create]
      resources :uploads, only: [:new, :create]

      #post 'upload_transcript', to: 'interviews#upload_transcript', as: :upload_transcript
      #get 'upload_transcript', to: 'interviews#upload_transcript', as: :upload_transcript

      put 'update_speakers/:id', to: 'interviews#update_speakers'

      resources :interviews do
        member do 
          get :doi_contents
          get :headings
          get :initials
          #get :references
          get :ref_tree
        end
        collection do 
          post :dois
          #get :stills
        end
        #resources :registry_entries, only: [:show]
        resources :contributions, only: [:create, :destroy]
        resources :photos, only: [:create, :update, :destroy]
        resources :registry_references, only: [:create, :update, :destroy]
        resources :segments, only: [:create, :update, :index, :destroy]
        resources :tapes do
          collection do
            get :playlist
          end
          member do
            get :transcript
          end
        end
      end

      resources :searches, only: [:new, :facets, :archive, :interview] do
        collection do
          get :facets
          get :archive
          get :export_archive_search
          get :interview
          get :registry_entry
        end
      end
    end

    resources :user_contents do
      collection do
        get :segment_annotation
        post :create_annotation
        post :sort
      end
      member do
        patch :publish
        get :topics
        post :retract
        put :update_topics
        put :update_annotation
        get :publish_notice
      end
    end

    resources :user_roles, only: [:create, :destroy]
    resources :roles
    resources :role_permissions, only: [:create, :destroy]
    resources :permissions
    resources :tasks

    namespace :admin do
      resources :users do
        collection do
          get :admin
        end
        member do
          post :flag
        end
      end
      resources :user_annotations do
        member do
          post :remove
          post :reject
          post :withdraw
          post :postpone
          post :accept
          post :review
        end
      end
      resources :user_statistics do
        collection do
          get :usage_report
        end
      end
     # get 'benutzerstatistik' => 'user_statistics#index', :as => :user_statistics
      resources :imports do
        collection do
          get :for_interview
        end
      end
    end
  end

  get 'photos/src/:name' => 'photos#src'
  get 'photos/thumb/:name' => 'photos#thumb'

end

app/models/search.rb
class Search < UserContent
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  layout 'responsive'

  skip_before_action :authenticate_user_account!
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped

  def facets
    json = Rails.cache.fetch "#{Project.cache_key_prefix}-search-facets-#{RegistryEntry.maximum(:updated_at)}" do
      {facets: Project.search_facets_hash}.to_json
    end

    respond_to do |format|
      format.json do
        render plain: json
      end
    end
  end

  def registry_entry
    search = RegistryEntry.search do 
      fulltext params[:fulltext].blank? ? "empty fulltext should not result in all registry_entries (this is a comment)" : params[:fulltext]
      #order_by(:names, :asc)
      paginate page: params[:page] || 1, per_page: 200
    end

    respond_to do |format|
      format.html do
        render :template => '/react/app.html'
      end
      format.json do
        render json: {
          result_pages_count: search.results.total_pages,
          results_count: search.total,
          registry_entries: search.results.map do |result| 
            Rails.cache.fetch("#{Project.cache_key_prefix}-registry_entry-#{result.id}-#{result.updated_at}-#{params[:fulltext]}") do 
              registry_entry = ::RegistryEntrySerializer.new(result).as_json 
              ancestors = result.ancestors.inject({}){|mem, a| mem[a.id] = ::RegistryEntrySerializer.new(a).as_json; mem }
              {registry_entry: registry_entry, ancestors: ancestors, bread_crumb: result.bread_crumb}
            end
          end,
          fulltext: params[:fulltext],
        }
      end
    end
  end

  def search(model, order)
    model.search do 
      fulltext params[:fulltext].blank? ? "empty fulltext should not result in all segments (this is a comment)" : params[:fulltext]  do
        (Project.available_locales + [:orig]).each do |locale|
          highlight :"text_#{locale}"
        end
      end
      with(:archive_id, params[:id])
      with(:workflow_state, (current_user_account && current_user_account.admin?) && model.respond_to?(:workflow_spec) ? model.workflow_spec.states.keys : 'public')
      order_by(order, :asc)
      paginate page: params[:page] || 1, per_page: 2000
    end
  end

  def found_instances(model, search)
    search.hits.select{|h| h.instance}.map do |hit| 
      instance = cache_single(hit.instance, model == Segment ? 'SegmentHit' : nil)
      instance[:text] = highlighted_text(hit)
      instance
    end
  end

  def interview
    models_and_order = [
      [Segment, :sort_key],
      [BiographicalEntry, :start_date],
      [Photo, :id],
      [Person, "name_#{locale}".to_sym]
    ]
      
    models_and_order.each do |model, order|
      instance_variable_set "@#{model.name.underscore}_search", search(model, order)
    end

    respond_to do |format|
      format.html do
        render :template => '/interviews/show'
      end
      format.json do
        interview = Interview.find_by_archive_id(params[:id])
        json = {
          fulltext: params[:fulltext],
          archiveId: params[:id]
        }
          
        models_and_order.each do |model, order|
          json["found_#{model.name.underscore.pluralize}"] = found_instances(model, instance_variable_get("@#{model.name.underscore}_search"))
        end

        render plain: json.to_json
      end
    end
  end

  # https://github.com/sunspot/sunspot#stored-fields
  def all_interviews_titles
    Rails.cache.fetch("#{Project.cache_key_prefix}-all_interviews_titles") do
      search = Interview.search do
        adjust_solr_params do |params|
          params[:rows] = Interview.all.size
        end
        with(:workflow_state, (current_user_account && current_user_account.admin?) ? Interview.workflow_spec.states.keys : 'public')
      end
      search.hits.map{ |hit| eval hit.stored(:title) }
      # => [{:de=>"Fomin, Dawid Samojlowitsch", :en=>"Fomin, Dawid Samojlowitsch", :ru=>"Фомин Давид Самойлович"},
      #    {:de=>"Jusefowitsch, Alexandra Maximowna", :en=>"Jusefowitsch, Alexandra Maximowna", :ru=>"Юзефович Александра Максимовна"},
      #    ...]
    end
  end

  # hagen only
  # in order to being able to get a dropdown list in search field
  def all_interviews_pseudonyms
    Rails.cache.fetch("#{Project.cache_key_prefix}-all_interviews_pseudonyms") do
      search = Interview.search do
        adjust_solr_params do |params|
          params[:rows] = Interview.all.size
        end
        with(:workflow_state, (current_user_account && current_user_account.admin?) ? Interview.workflow_spec.states.keys : 'public')
      end
      ps = search.hits.map{ |hit| {:de => RegistryEntry.find(hit.stored :pseudonym ).first.registry_names.first.try(:descriptor)} if hit.stored(:pseudonym).try(:first)}
      ps.compact
    end
  end

  def all_interviews_places_of_birth
    Rails.cache.fetch("#{Project.cache_key_prefix}-all_interviews_places_of_birth") do
      search = Interview.search do
        adjust_solr_params do |params|
          params[:rows] = Interview.all.size
        end
        with(:workflow_state, (current_user_account && current_user_account.admin?) ? Interview.workflow_spec.states.keys : 'public')
      end
      search.hits.map {|hit| hit.stored(:place_of_birth) }
    end
  end

  def export_archive_search
    search = Interview.search do
      adjust_solr_params do |params|
        params[:rows] = 1000
      end
      fulltext params[:fulltext]
      Project.search_facets_names.each do |facet|
        with(facet.to_sym).any_of(params[facet]) if params[facet]
      end
      with(:workflow_state, (current_user_account && current_user_account.admin?) ? Interview.workflow_spec.states.keys : 'public')
      facet *Project.search_facets_names
      order_by("person_name_#{locale}".to_sym, :asc) if params[:fulltext].blank?
    end

    respond_to do |format|
      format.csv do
        desired_columns = [:archive_id, [:short_title,:de], :media_type]
        options = {}
        csv = CSV.generate(options) do |csv|
          # csv << desired_columns.map{|c| c.to_s}
          csv << ["ID", "Titel", "Medientyp"]
          search.results.each do |interview|
            csv << desired_columns.map{ |c| interview.send(*c) }
          end
        end
        send_data csv
      end
      format.json do
        render json: {
            interviews: search.results,
        }
      end

    end
  end

  def archive
    search = Interview.search do
      fulltext params[:fulltext]
      Project.search_facets_names.each do |facet|
        with(facet.to_sym).any_of(params[facet]) if params[facet]
      end
      with(:workflow_state, (current_user_account && current_user_account.admin?) ? Interview.workflow_spec.states.keys : 'public')
      facet *Project.search_facets_names
      order_by("person_name_#{locale}".to_sym, :asc) if params[:fulltext].blank?
      # TODO: sort linguistically
      paginate page: params[:page] || 1, per_page: 12
    end

    # number_of_found_segments = search.hits.inject({}) do |mem, hit|
    #   segsearch = Segment.search do
    #     fulltext params[:fulltext].blank? ? "empty fulltext should not result in all segments (this is a comment)" : params[:fulltext]
    #     with(:archive_id, hit.instance.archive_id)
    #   end
    #   mem[hit.instance.archive_id] = segsearch.total
    #   mem
    # end

    # found_segments = search.hits.inject({}) do |mem, hit|
    #   segsearch = Segment.search do
    #     adjust_solr_params do |params|
    #       params[:rows] = 5
    #     end
    #     fulltext params[:fulltext].blank? ? "empty fulltext should not result in all segments (this is a comment)" : params[:fulltext] do
    #       highlight :transcript
    #       highlight :translation
    #     end
    #     with(:archive_id, hit.instance.archive_id)
    #   end

    #   interview = hit.instance
      
    #   mem[interview.archive_id] = {
    #     total: segsearch.total,
    #     segments: segsearch.hits.map do |hit| 
    #       # Rails.cache.fetch("#{Project.cache_key_prefix}-segment-#{hit.instance.id}-#{hit.instance.updated_at}") do 
    #       segment = ::SegmentHitSerializer.new(hit.instance).as_json 
    #       segment[:transcripts] = highlighted_transcripts(hit, interview)
    #       segment
    #       # end
    #     end
    #   }
    #   mem
    # end

    respond_to do |format|
      format.html do
        render :template => '/react/app.html'
      end
      format.json do
        render json: {
            all_interviews_titles: all_interviews_titles,
            all_interviews_pseudonyms: all_interviews_pseudonyms,
            all_interviews_places_of_birth: all_interviews_places_of_birth,
            all_interviews_count: Interview.count,
            result_pages_count: search.results.total_pages,
            results_count: search.total,
            interviews: search.results.map{|i| cache_single(i)},
            # found_segments_for_interviews: number_of_found_segments,
            # found_segments_for_interviews: found_segments,
            facets: Project.updated_search_facets(search),
            page: params[:page] || 1
        }
      end
    end
  end

  private

  def highlighted_text(hit) 
    (Project.available_locales + [:orig]).inject({}) do |mem, locale|
      # locale = hit.instance.orig_lang if locale == :orig
      mem[locale] = hit.highlights("text_#{locale}").inject([]) do |m, highlight|
        highlighted = highlight.format { |word| "<span class='highlight'>#{word}</span>" }
        m << highlighted.sub(/:/,"").strip()
        m
      end.join(' ').gsub("&nbsp;", " ").strip
      mem
    end
  end
end

app/views/searches/_active_facet.html.erb
<% facet_dom_id = "selected_#{active_facet}" %>
<% query = query.to_a unless query.is_a?(Array) %>
<% is_category = Project.is_category?(active_facet) %>
<% human_readable_facet_name = (is_category ? Project.category_name(active_facet, I18n.locale) : t(active_facet.singularize, :scope => :facets)) %>
<div id="<%= facet_dom_id %>" class="active-facet">
  <span class="facet-name"><%= human_readable_facet_name %>:</span>

  <ul>
  <% if is_category or active_facet == 'language_id' %>

    <% clazz = (is_category ? RegistryEntry : Language) %>
    <% query = query.map{|c| c.to_i != 0 ? begin; clazz.find(c); rescue; nil; end : nil }.compact %>

    <% query.each_with_index do |category, index| %>
      <li><%= category.to_s -%><%= (index == query.size-1) ? '' : ','-%></li>
    <% end %>

  <% elsif active_facet == 'interview_id' %>

    <% query = query.map{|i| i.to_i != 0 ? begin; Interview.find(i); rescue; nil; end : nil }.compact %>

    <% query.each do |interview| %>
      <% interview.full_title(I18n.locale).split(' ').each do |name_token| %>
        <li><%= name_token %></li>
      <% end %>
    <% end %>

  <% end %>
  </ul>

  <%= link_to 'entfernen', class: 'facet-remove', title: t('.remove'), remove: "#{query.map{|facet_object| "##{active_facet}_#{facet_object[:id]}" }" %> 

  <fieldset style="display:none" id="<%= active_facet %>_query" class="facet-field">

    <% query.each do |facet_object| %>
      <%= hidden_field_tag "#{active_facet}[]", facet_object[:id], { :id => "#{active_facet}_#{facet_object[:id]}"} %>
    <% end %>

  </fieldset>
</div>

app/views/searches/_facet_option.html.erb
<% facet_id = facet_option.first.to_sym %>
<% facet_name = facet_id.to_s %>
<% facet_entries = facet_option.last %>
<% category_facet = Project.is_category?(facet_id) %>
<% human_readable_facet_name = (category_facet ? Project.category_name(facet_id, I18n.locale) : t(facet_name.singularize, :scope => :facets)) %>
<% item_list = !category_facet && (facet_entries.size < 13) %>
<% facet_closed = ((search_facets.object.send(facet_id) || []).empty? and search_facets.object.open_category != facet_name) %>

  <div id="<%= facet_name %>" class="fragmentTitle <%= facet_closed ? 'closed' : 'open'%>">

    <% if category_facet && facet_entries.empty? %>

      <h2 class='more disabled'>
        <img title="" src="<%= image_path "#{Project.name}/pfeil_rot_rechts.gif" %>" id="<%= facet_name %>_query_closed" alt="<%= t('.arrow_right') %>" />
        <%= human_readable_facet_name %>
      </h2>

    <% else %>

      <h2 onclick="toggleCategory('<%= facet_name %>_query', <%= category_facet || item_list %>);" class="more <%= (category_facet && facet_entries.empty?) ? 'disabled' : '' %>">

        <img title="" src="<%= image_path  "#{Project.name}/pfeil_rot_rechts.gif" %>" id="<%= facet_name %>_query_closed" class="arrow-closed" alt="<%= t('.arrow_right') %>" />
        <img title="" src="<%= image_path  "#{Project.name}/pfeil_rot_unten.gif" %>" id="<%= facet_name %>_query_open" class="arrow-open" alt="<%= t('.arrow_down') %>" />
        <%= human_readable_facet_name %>
        <%= search_facets.submit '&uuml;bernehmen', :style => 'display: none;', :type => 'image', :src => image_path("#{Project.name}/suchpfeil_quad_grau.gif"), :title => t('.update'), :class => 'facet_refresh', :id => "#{facet_name}_submit", :onclick => "submitViaAjax();false;" %>
      </h2>
      <fieldset style="<%= facet_closed ? 'display: none;' : ''%>" id="<%= facet_name %>_query" class="facet-field">

          <% if category_facet or facet_id == :language_id %>

            <% current_categories = search_facets.object.send(facet_id) || [] %>

            <ul>
              <% facet_entries.each do |f| %>

                <% category = f.first %>

                <li class="facet<%= current_categories.include?(category[:id]) ? ' checked' : '' %>" onclick="checkCategory('<%= "#{facet_name}_#{category[:id]}" %>', this);" id="<%= "facet_#{facet_name}_#{category[:id]}" -%>">
                    <%= check_box_tag "#{facet_name}[]", category[:id], current_categories.include?(category[:id]), { :id => "#{facet_name}_#{category[:id]}", :class => (facet_name + ' checkbox') } %>
                    <span class="facet-name"><%= category.to_s %></span>
                    <% if f.last != 0 %>
                      <span class="facet-count">(<%= f.last %>)</span>
                    <% end %>
                </li>

              <% end %>
            </ul>

          <% elsif facet_id == :interview_id %>

            <% if item_list and !facet_entries.empty? %>

              <ul>
                <% facet_entries.each do |name| %>
                  <li><%= link_to name.first.full_title(I18n.locale), new_search_url(interview_id: [name.first.id]), method: :get, remote: true %></li>
                <% end %>
              </ul>

            <% else %>

              <%= search_facets.text_field :person_name, { :size => 25, :name => 'person_name', :class => 'searchInput' } %>
              <div id="empty-message"></div>

              <%= javascript_tag do %>
                    jQuery.noConflict();
                jQuery('#search_person_name').autocomplete({
                  source: '<%= person_name_searches_path @search.query_params.reject{|k,v| k == 'page'} -%>',
                  minLength: 2,
                  select: function( event, ui ) {
                    // asynchronously submit the form - this is necessary
                    // for the form input to transfer the assigned value
                    // when clicking on it.
                    $this = jQuery(this)
                    setTimeout( function() { $this.closest('form').submit(); }, 0 );
                  },
                  response: function(event, ui) {
                    if (ui.content.length === 0) {
                      jQuery("#empty-message").text('<%=t '.no_persons_found' %>');
                    } else {
                      if (ui.content.length === 1 && ui.content[0]['label'] === 'redirect_to') {
                        // This is a special redirect message after an unauthorized access.
                        window.location.href = ui.content[0]['value']
                        // Remove the fake message to avoid it being temporarily shown to the user.
                        ui.content.pop()
                      } else {
                        // We got a normal result list.
                        jQuery("#empty-message").empty();
                      }
                    }
                  }
                });
              <% end %>

            <% end %>

          <% end %>
      </fieldset>

    <% end %>

  </div>

app/views/searches/_facets.html.erb
<div id="searchReset">
  <% if facets.hits < Interview.count %>
      <%= reset_search_link({:before => "beforeSubmit();"}) %>
  <% end %>
</div>

<div class="baseListBox">

  <%= form_for facets,
               url: new_search_path,
               method: 'get',
               #:remote => true,
               html: { id: 'search_facets', name: 'searchFacets'}  do |search_facets| %>


      <div class="fragmentTitle">
        <% current_search_text = (search_facets.object.fulltext.blank?) ? t('search_term', :scope => 'user_interface.search') : search_facets.object.fulltext -%>
        <%= search_facets.text_field :fulltext, :value => current_search_text, :name => 'fulltext', :id => 'searchInput', :class => 'baseInputSearch searchInput', :title => t('fulltext_title', :scope => 'user_interface.search'), :onFocus => "clearFulltextField('searchInput');" %>
        <%= search_facets.submit 'suchen', :class => 'search', :id => 'searchButton', :alt => t('.search'), :type => :image, :src => image_path("#{Project.name}/pfeil_rot_rechts.gif"), :onclick => "submitViaAjax(); false;" %>
        <%= hidden_field_tag 'open_category', '', :id => 'open_category' %>

      </div>

      <noscript>
        <div class="warning">
          <h4><%= t('search_no_javascript', :scope => 'user_interface.messages') %></h4>
        </div>
      </noscript>

      <% facets.query_facets.each do |facet| %>
          <%= render :partial => '/searches/active_facet', :object => facet.first, :locals => {:query => facet.last} %>
      <% end %>

      <% facets.unqueried_facets.each do |facet| %>
          <%= render :partial => '/searches/facet_option', :object => facet, :locals => {:search_facets => search_facets, :category_facet => facets.send(facet.first).is_a?(Array)} %>
      <% end %>

  <% end %>

  <% unless facets.open_category.blank? %>
      <%= javascript_tag do %>
          toggleCategory('<%= facets.open_category %>_query', true);
      <% end %>
  <% end %>

  <%= javascript_tag do %>
      Event.observe(document, 'keypress', function(event){ if(event.keyCode == Event.KEY_RETURN) { /* catch these
      keycodes to submit the forms! */ }} );
  <% end %>

</div>

app/views/searches/_search.html.erb
<h2 class="info">Service-Funktionen</h2>
<p class="mainSearch"><%= link_to t(:search_the_archive, :scope => 'user_interface.labels'), current_search_path %></p>
<div id="baseHeaderSearch">
  <span class="hits">
    <% if search.hits == Interview.count %>
      <%= link_to t('.all_interviews').html_safe, current_search_path %>
    <% elsif search.hits > 1 %>
      <%= link_to t('.many_selected', :search_hits => search.hits).html_safe, current_search_path %>
    <% elsif search.hits == 1 %>
      <%= link_to t('.one_selected').html_safe, current_search_path %>
    <% else %>
      <%= t('.no_interviews_found').html_safe %>
    <% end %>
  </span>
</div>

<div id="submit_search" class="action">
  <%= submit_tag t(:search, :scope => 'user_interface.labels'), :type => :image, :src => image_path("#{Project.name}/suchpfeil_quad.gif"), :onclick => 'submitViaAjax(); false;' %>
</div>

<div id="search_header_overlay" class="overlay" style="display: none;"></div>

<%= javascript_tag do %>
    var queryHash = '<%= (@search || Search.new).query_hash || '' %>';
    <% if action_name == 'new' && controller_name == 'searches' %>
    document.observe("dom:loaded", submitHashedQueryParams());
    <% end %>
<% end %>

app/views/searches/index.js.erb
jQuery('#innerContent').html('<%= escape_javascript(render template: '/interviews/index.html', layout: false) %>')
jQuery('#baseServices').html('<%= escape_javascript(render partial: '/searches/search.html', object: @search, layout: false) %>')
jQuery('#baseContainerRight').html('<%= escape_javascript(render partial: '/searches/facets.html', object: @search, layout: false) %>')

app/views/searches/interview.js.erb
jQuery('#search-results').html('<%= escape_javascript(render(partial: '/interviews/segments.html', layout: false)) %>');
jQuery("#search-results-toggle").find('.hits').html('(<%= @segments.size %>)');

app/views/searches/new.html.erb
<%# This template is used for the non-js full search capability %>